version: "3"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8181:8181
    depends_on:
      - server

  locator:
    image: apachegeode/geode
    hostname: locator
    mem_limit: 512m
    ports:
      - "1099:1099"
      - "10334:10334"
      - "7575:7575"
      - "7070:7070"
    volumes:
      - ./scripts/:/scripts/
    command: /scripts/gfshWrapper.sh gfsh start locator --name=locator --mcast-port=0
    environment:
      - GEODE_NODE_NAME=geode
      - GEODE_ADVERTISED_HOSTNAME=localhost
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes

  server:
    image: apachegeode/geode
    mem_limit: 2g
    links:
      - locator:locator
    expose:
      - "8080"
      - "40404"
      - "1099"
    ports:
      - "40404:40404"
    volumes:
      - ./scripts/:/scripts/
    command: /scripts/startServer.sh --server-port=40404 --max-heap=1G
    environment:
      - GEODE_NODE_NAME=geode
      - GEODE_ADVERTISED_HOSTNAME=localhost
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
